import React, { createContext, useState, useContext, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    explore: 'Explore',
    music: 'Music',
    solution: 'Solutions',
    language: 'English',
    devotional: 'Devotional',
    search: 'Search bhajans...',
    all: 'All',
    bhajan: 'Bhajan',
    mantra: 'Mantra',
    aarti: 'Aarti',
    tracksFound: 'Tracks Found',
    spiritualSongs: 'Spiritual Songs',
    removeFavoriteTitle: 'Remove Favorite',
    removeFavoriteMessage: 'Are you sure you want to remove this from your favorites?',
    audio: 'Audio',
    video: 'Video',
    lyrics: 'Lyrics',
    lyricsNotAvailable: 'Lyrics not available for this Aarti.',
    favorites: 'Favorites',
    categories: 'Categories',
    divineQuoteTitle: 'Divine Quote of the Day',
    spiritualTools: 'Spiritual Tools',
    festivalCalendar: 'Festival Calendar',
    calendar: 'Calendar',
    aartiSangrah: 'Aarti Sangrah',
    aartiIntro: 'Immerse yourself in the divine grace with our curated collection of Aarti and lyrics.',
    comingSoon: 'Coming Soon',
    watching: 'Watching',
    connecting: 'Connecting...',
    playing: 'Playing',
    paused: 'Paused',
    bhajans: 'Bhajans',
    mantras: 'Mantras',
    aartis: 'Aartis',
    loading: 'Loading...',
    noData: 'No data available',
    settings: 'Settings',
    profile: 'Profile',
    about: 'About Us',
    logout: 'Logout',
    login: 'Login / Create Account',
    logoutConfirm: 'Are you sure you want to sign out?',
    cancel: 'Cancel',
    error: 'Error',
    success: 'Success',
    ok: 'Okay',
    nameEmpty: 'Name cannot be empty',
    profileUpdated: 'Profile updated successfully',
    spiritualLibrary: 'Spiritual Library',
    searchPlaceholder: 'Search for divine melodies...',
    retry: 'Try Again',
    // Categories & Deities
    Krishna: 'Krishna',
    Shiv: 'Shiv',
    Mahadev: 'Mahadev',
    Laxmi: 'Laxmi',
    Ram: 'Ram',
    Hanuman: 'Hanuman',
    Ganesh: 'Ganesh',
    Devi: 'Devi',
    Durga: 'Durga',
    Saraswati: 'Saraswati',
    'Mangal Dosh': 'Mangal Dosh',
    'Shani Dosh': 'Shani Dosh',
    'Rahu Dosh': 'Rahu Dosh',
    'Kaal Sarp': 'Kaal Sarp',
    All: 'All',
    deity: 'Deities',
    dosh: 'Dosh Guidance',
    deities: 'Devotional Deities',
    kundliDosh: 'Kundli Dosh Guidance',
    devotionalSelection: 'Devotional Selection',
    astrologicalGuide: 'Astrological Guide',
    solutionTitle: 'Spiritual Solutions',
    watchVideo: 'Watch Video Solution',
    Health: 'Health',
    Wealth: 'Wealth',
    Job: 'Job',
    Family: 'Family',
    Peace: 'Peace',
    theme: 'App Theme',
    themeSystem: 'System Default',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    aboutApp: 'About MantraPuja Bhajan',
    removeFavTitle: 'Remove from Favorites',
    removeFavMsg: 'Do you want to remove this from your divine collection?',
    remove: 'Remove',
    trackFound: 'Track Found',
    tracksFound: 'Tracks Found',
    bhajanVideo: 'Video Bhajans',
    bhajanAudio: 'Audio Bhajans',
    upayeVideo: 'Video Upaye',
    upayeAudio: 'Audio Upaye',
    noLikedItems: 'No Liked Items',
    saveFavoriteDivine: 'Save your favorite divine content to listen to them anytime.',
    readMore: 'Read More',
    loginRequired: 'Login Required',
    loginPrompt: 'Sign in to sync your favorite divine melodies across all your devices.',
    signInNow: 'Sign In Now',
    editProfile: 'Edit Profile',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    saveChanges: 'Save Changes',
    namaste: 'Namaste!',
    verifyWhatsApp: 'Verify WhatsApp',
    createProfile: 'Create your profile',
    signInWhatsApp: 'Sign in via WhatsApp OTP',
    enterCodeSent: 'Enter the code sent to',
    whatsappNumber: 'WhatsApp Number',
    yourName: 'Your Name',
    getWhatsAppOtp: 'Get WhatsApp OTP',
    enterOtp: 'Enter 6-digit OTP',
    verifyLogin: 'Verify & Login',
    resendOtp: 'Resend OTP',
    resendIn: 'Resend OTP in',
    changePhone: 'Change Phone Number',
    invalidPhone: 'Invalid Phone',
    enterValidPhone: 'Please enter a valid 10-digit phone number.',
    nameRequired: 'Name Required',
    enterYourName: 'Please enter your name.',
    invalidOtp: 'Invalid OTP',
    enterSixDigit: 'Please enter the 6-digit code.',
    verificationFailed: 'Verification Failed',
    next: 'Next',
    suggestedCategories: 'Suggested Categories',
    searchResults: 'Search Results',
    noResults: 'No Results',
    ourVision: 'Our Vision',
    visionDescription: 'MantraPuja Bhajan is a comprehensive platform for booking Hindu pujas (rituals), astrology readings, and spiritual services online. Our mission is to make authentic Vedic rituals accessible to everyone, everywhere. Explore our vast library of bhajans, mantras, and devotional content.',
    authenticRituals: 'Authentic Vedic Rituals',
    expertAstrologers: 'Expert Astrologers',
    spiritualLib: 'Spiritual Library',
    getInTouch: 'Get In Touch',
    versionLabel: 'Version',
    allRightsReserved: 'All rights reserved.',
    shareApp: 'Share App',
    rateApp: 'Rate App',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    play: 'Play',
    pause: 'Pause',
    nextTrack: 'Next',
    prevTrack: 'Previous',
    shuffle: 'Shuffle',
    repeat: 'Repeat',
    addToPlaylist: 'Add to Playlist',
    viewLyrics: 'View Lyrics',
  },
  hi: {
    home: 'होम',
    explore: 'खोजें',
    music: 'संगीत',
    solution: 'समाधान',
    language: 'हिंदी',
    devotional: 'भक्ति',
    search: 'भजन खोजें...',
    all: 'सभी',
    bhajan: 'भजन',
    mantra: 'मंत्र',
    aarti: 'आरती',
    tracksFound: 'भजन मिले',
    spiritualSongs: 'आध्यात्मिक गीत',
    removeFavoriteTitle: 'पसंदीदा से हटाएं',
    removeFavoriteMessage: 'क्या आप वाकई इसे अपने पसंदीदा से हटाना चाहते हैं?',
    audio: 'ऑडियो',
    video: 'वीडियो',
    lyrics: 'लिरिक्स',
    lyricsNotAvailable: 'इस आरती के लिए लिरिक्स उपलब्ध नहीं हैं।',
    favorites: 'पसंदीदा',
    categories: 'श्रेणियाँ',
    divineQuoteTitle: 'आज का दिव्य विचार',
    spiritualTools: 'आध्यात्मिक साधन',
    festivalCalendar: 'त्योहार कैलेंडर',
    calendar: 'कैलेंडर',
    aartiSangrah: 'आरती संग्रह',
    aartiIntro: 'आरती और लिरिक्स के हमारे विशेष संग्रह के साथ दिव्य कृपा में लीन हों।',
    comingSoon: 'जल्द आ रहा है',
    watching: 'देख रहे हैं',
    connecting: 'कनेक्ट हो रहा है...',
    playing: 'बज रहा है',
    paused: 'रुका हुआ',
    bhajans: 'भजन',
    mantras: 'मंत्र',
    aartis: 'आरतियां',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा नहीं मिला',
    settings: 'सेटिंग्स',
    profile: 'प्रोफ़ाइल',
    about: 'हमारे बारे में',
    logout: 'लॉगआउट',
    login: 'लॉगिन / नया अकाउंट बनाएं',
    logoutConfirm: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    cancel: 'रद्द करें',
    error: 'त्रुटि',
    success: 'सफलता',
    ok: 'ठीक है',
    nameEmpty: 'नाम खाली नहीं हो सकता',
    profileUpdated: 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई',
    spiritualLibrary: 'आध्यात्मिक पुस्तकालय',
    searchPlaceholder: 'भजन या मंत्र खोजें...',
    retry: 'फिर कोशिश करें',
    // Categories & Deities
    Krishna: 'कृष्ण',
    Shiv: 'शिव',
    Mahadev: 'महादेव',
    Laxmi: 'लक्ष्मी',
    Ram: 'राम',
    Hanuman: 'हनुमान',
    Ganesh: 'गणेश',
    Devi: 'देवी',
    Durga: 'दुर्गा',
    Saraswati: 'सरस्वती',
    'Mangal Dosh': 'मंगल दोष',
    'Shani Dosh': 'शनि दोष',
    'Rahu Dosh': 'राहु दोष',
    'Kaal Sarp': 'काल सर्प दोष',
    All: 'सभी',
    deity: 'देवी-देवता',
    dosh: 'दोष मार्गदर्शन',
    deities: 'भक्तिमय देवी-देवता',
    kundliDosh: 'कुंडली दोष मार्गदर्शन',
    devotionalSelection: 'भक्तिमय चयन',
    astrologicalGuide: 'ज्योतिषीय मार्गदर्शन',
    solutionTitle: 'आध्यात्मिक समाधान',
    watchVideo: 'वीडियो समाधान देखें',
    Health: 'स्वास्थ्य',
    Wealth: 'धन-सम्पत्ति',
    Job: 'नौकरी/व्यवसाय',
    Family: 'परिवार',
    Peace: 'शांति',
    theme: 'ऐप थीम',
    themeSystem: 'सिस्टम डिफ़ॉल्ट',
    themeLight: 'लाइट मोड',
    themeDark: 'डार्क मोड',
    aboutApp: 'मंत्रपूजा भजन के बारे में',
    removeFavTitle: 'पसंदीदा से हटाएं',
    removeFavMsg: 'क्या आप इसे अपने संग्रह से हटाना चाहते हैं?',
    remove: 'हटाएं',
    trackFound: 'भजन मिला',
    tracksFound: 'भजन मिले',
    bhajanVideo: 'वीडियो भजन',
    bhajanAudio: 'ऑडियो भजन',
    upayeVideo: 'वीडियो उपाय',
    upayeAudio: 'ऑडियो उपाय',
    noLikedItems: 'कोई पसंदीदा आइटम नहीं',
    saveFavoriteDivine: 'अपनी पसंदीदा दिव्य सामग्री को किसी भी समय सुनने के लिए सहेजें।',
    readMore: 'और पढ़ें',
    loginRequired: 'लॉगिन आवश्यक',
    loginPrompt: 'अपनी पसंदीदा दिव्य धुनों को अपने सभी उपकरणों पर सिंक करने के लिए साइन इन करें।',
    signInNow: 'अभी साइन इन करें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    fullName: 'पूरा नाम',
    phoneNumber: 'फ़ोन नंबर',
    saveChanges: 'परिवर्तन सहेजें',
    namaste: 'नमस्ते!',
    verifyWhatsApp: 'व्हाट्सएप सत्यापित करें',
    createProfile: 'अपनी प्रोफ़ाइल बनाएं',
    signInWhatsApp: 'व्हाट्सएप ओटीपी के माध्यम से साइन इन करें',
    enterCodeSent: 'भेजा गया कोड दर्ज करें',
    whatsappNumber: 'व्हाट्सएप नंबर',
    yourName: 'आपका नाम',
    getWhatsAppOtp: 'ओटीपी प्राप्त करें',
    enterOtp: '6-अंकीय ओटीपी दर्ज करें',
    verifyLogin: 'सत्यापित करें और लॉगिन करें',
    resendOtp: 'ओटीपी पुनः भेजें',
    resendIn: 'ओटीपी पुनः भेजें',
    changePhone: 'फ़ोन नंबर बदलें',
    invalidPhone: 'अमान्य फ़ोन',
    enterValidPhone: 'कृपया एक मान्य 10-अंकीय फ़ोन नंबर दर्ज करें।',
    nameRequired: 'नाम आवश्यक है',
    enterYourName: 'कृपया अपना नाम दर्ज करें।',
    invalidOtp: 'अमान्य ओटीपी',
    enterSixDigit: 'कृपया 6-अंकीय कोड दर्ज करें।',
    verificationFailed: 'सत्यापन विफल',
    next: 'आगे बढ़ें',
    suggestedCategories: 'सुझाई गई श्रेणियाँ',
    searchResults: 'खोज परिणाम',
    noResults: 'कोई परिणाम नहीं',
    ourVision: 'हमारा दृष्टिकोण',
    visionDescription: 'मंत्रपूजा भजन हिंदू पूजाओं (अनुष्ठानों), ज्योतिष रीडिंग और आध्यात्मिक सेवाओं की ऑनलाइन बुकिंग के लिए एक व्यापक मंच है। हमारा मिशन वैदिक अनुष्ठानों को हर जगह, हर किसी के लिए सुलभ बनाना है। भजनों, मंत्रों और भक्ति सामग्री की हमारी विशाल लाइब्रेरी का आनंद लें।',
    authenticRituals: 'प्रामाणिक वैदिक अनुष्ठान',
    expertAstrologers: 'विशेषज्ञ ज्योतिषी',
    spiritualLib: 'आध्यात्मिक पुस्तकालय',
    getInTouch: 'संपर्क करें',
    versionLabel: 'संस्करण',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    shareApp: 'ऐप साझा करें',
    rateApp: 'ऐप को रेट करें',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    play: 'चलाएं',
    pause: 'रोकें',
    nextTrack: 'अगला',
    prevTrack: 'पिछला',
    shuffle: 'शफल',
    repeat: 'दोहराएं',
    addToPlaylist: 'प्लेलिस्ट में जोड़ें',
    viewLyrics: 'लिरिक्स देखें',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const saved = await AsyncStorage.getItem('user_language');
      if (saved) setLanguage(saved);
    } catch (e) {
      console.log('Error loading language', e);
    }
  };

  const toggleLanguage = async () => {
    const newLang = language === 'en' ? 'hi' : 'en';
    setLanguage(newLang);
    try {
      await AsyncStorage.setItem('user_language', newLang);
    } catch (e) {
      console.log('Error saving language', e);
    }
  };

  const t = (key) => {
    if (!key) return '';
    // Try exact match first, then lowercase match
    const langSet = translations[language];
    if (langSet[key]) return langSet[key];
    
    // Fallback for case-insensitive matching (e.g. mahadev -> Mahadev)
    const foundKey = Object.keys(langSet).find(k => k.toLowerCase() === key.toLowerCase());
    return foundKey ? langSet[foundKey] : key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
